EventPro.Web/Controllers/EventLocationController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using EventPro.DAL.Models;
using EventPro.Web.Common;
using EventPro.Web.Filters;
using EventPro.Web.Services;
using System.Linq;
using System.Threading.Tasks;

namespace EventPro.Web.Controllers
{
    /*
     * Unforunately, no authentication scheme is specified yet.
     * So I have to use the indian company method to verify logging in and roles
     * till this point.
     */
    public class EventLocationController : Controller
    {
        readonly EventProContext _context;

        public EventLocationController(EventProContext context)
        {
            _context = context;
        }

        // GET: EventLocationController
        [AuthorizeRoles("Administrator", "Operator", "Supervisor")]
        public async Task<IActionResult> Index()
        {
            ViewBag.PageTitle = "Events Locations";
            return View(await _context.EventLocations.ToListAsync());
        }

        // GET: EventLocationController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EventLocationController/Create
        [HttpPost]
        [AuthorizeRoles("Administrator", "Operator", "Supervisor")]
        //  [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormCollection collection)
        {
            try
            {
                var _city = collection["city"].FirstOrDefault();
                var _governorate = collection["governorate"].FirstOrDefault();
                var _country = collection["country"].FirstOrDefault();
                var locations = await _context.EventLocations.FirstOrDefaultAsync(l => l.Country.ToLower() == _country.ToLower()
                                                                && l.Governorate.ToLower() == _governorate.ToLower()
                                                                && l.City.ToLower() == _city.ToLower());
                if (locations == null)
                {
                    await _context.EventLocations.AddAsync(new EventLocation
                    {
                        City = _city,
                        Governorate = _governorate,
                        Country = _country
                    });
                    await _context.SaveChangesAsync();
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EventLocationController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            return View(await _context.EventLocations.FirstOrDefaultAsync(x => x.Id == id));
        }

        // POST: EventLocationController/Edit/5
        [HttpPost]
        [AuthorizeRoles("Administrator", "Operator", "Supervisor")]
        // [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, IFormCollection collection)
        {
            try
            {
                var old = await _context.EventLocations.FirstOrDefaultAsync(x => x.Id == id);

                var _city = collection["city"].FirstOrDefault();
                var _governorate = collection["governorate"].FirstOrDefault();
                var _country = collection["country"].FirstOrDefault();
                var locations = await _context.EventLocations.FirstOrDefaultAsync(l => l.Id != old.Id
                                                                && l.Country.ToLower() == _country.ToLower()
                                                                && l.Governorate.ToLower() == _governorate.ToLower()
                                                                && l.City.ToLower() == _city.ToLower());
                if (locations == null)
                {
                    old.City = _city;
                    old.Governorate = _governorate;
                    old.Country = _country;
                    await _context.SaveChangesAsync();
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        /*
        // GET: EventLocationController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }
        */

        // POST: EventLocationController/Delete/5
        [HttpGet]
        [AuthorizeRoles("Administrator", "Operator", "Supervisor")]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _context.EventLocations.Where(x => x.Id == id).ExecuteDeleteAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

EventPro.Web/Views/EventLocation/Create.cshtml
@using EventPro.DAL.Models;
@model EventLocation
@{
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<div class="container row p-5">
    @using (Html.BeginForm("Create", "EventLocation", FormMethod.Post))
    {
        <span>City:</span> @Html.TextBoxFor(m => m.City) <br />
        <span>Governorate:</span> @Html.TextBoxFor(m => m.Governorate) <br />
        <span>Country:</span> @Html.TextBoxFor(m => m.Country) <br />
        <input type="submit" value="Add Location" class="btn btn-primary">
    }
</div>

EventPro.Web/Views/EventLocation/Edit.cshtml
@using EventPro.DAL.Models;
@model EventLocation
@{
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<div class="container row p-5">
    @using (Html.BeginForm("Edit", "EventLocation", FormMethod.Post))
    {
        <span>City:</span> @Html.TextBoxFor(m => m.City) <br />
        <span>Governorate:</span> @Html.TextBoxFor(m => m.Governorate) <br />
        <span>Country:</span> @Html.TextBoxFor(m => m.Country) <br />
        <input type="submit" value="Save Location" class="btn btn-primary">
    }
</div>

EventPro.Web/Views/EventLocation/Index.cshtml
@using EventPro.DAL.Models;
@model List<EventLocation>

@{
    Layout = "~/Views/Shared/_Admin.cshtml";
}
<!-- Content Wrapper. Contains page content -->
<!-- /.content-header -->
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <a class="btn btn-primary" href="~/EventLocation/Create">Add New Location</a>
        <br />
        <br />
        <table id="searchableTable" class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>City</th>
                    <th>Governorate</th>
                    <th>Country</th>
                    <th>Options</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var eventLocation in Model)
                {
                    <tr>
                        <td>@eventLocation.Id</td>
                        <td>@eventLocation.City</td>
                        <td>@eventLocation.Governorate</td>
                        <td>@eventLocation.Country</td>
                        <td>
                            @if(@eventLocation.City != "Other")
                            {
                                <a href="/EventLocation/Edit/@eventLocation.Id" class="btn btn-primary">Edit</a>
                                <a href="/EventLocation/Delete/@eventLocation.Id" class="btn btn-primary">Delete</a>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
<!-- /.content-wrapper -->